# this maps Lacy IDs to Dracor-friendly filenames
# there should be an entry here for every title included in the sample
# some files are commented out because they fail validation
mv L0001.xml courtney-timetriesall.xml
mv L0012.xml brooks-thecreole.xml
mv L0013.xml taylor-noveltyfair.xml
mv L0039.xml courtney-belphegor.xml
mv L0042R.xml townley-highlife.xml
mv L0044.xml brooks-theexposition.xml
mv L0048.xml brough-apartments.xml
mv L0053.xml brooks-anythingforachange.xml
mv L0057R.xml massinger-anewwaytopayolddebts.xml
mv L0066.xml morton-athumpinglegacy.xml
mv L0073.xml morton-boxandcox.xml
mv L0075.xml phillips-anorganicaffection.xml
mv L0076.xml coyne-aduelinthedark.xml
mv L0082.xml barrymore-elhyder.xml
mv L0105.xml phillips-themasterpassion.xml
mv L0106.xml boucicault-theprimadonna.xml
mv L0113.xml coyne-boxandcoxmarried.xml
mv L0118.xml morton-betseybaker.xml
mv L0124.xml planche-theloanofalover.xml
mv L0127.xml barnett-thebolddragoons.xml
mv L0132.xml shakespeare-macbeth.xml
mv L0142.xml dimond-stagestruck.xml
mv L0144.xml morton-adesperategame.xml
mv L0157.xml planche-ahandsomehusband.xml
#mv L0159.xml talfourd-shylock.xml
mv L0170.xml planche-thecampattheolympic.xml
mv L0179.xml fitzball-themillerofderwent.xml
mv L0191.xml taylor-plotandpassion.xml
mv L0197.xml coyne-willikindandhisdinah.xml
mv L0201.xml planche-thejacobite.xml
mv L0206.xml poole-twouldpuzzleaconjuror.xml
mv L0219.xml morton-waitingforanomnibus.xml
mv L0228.xml johnstone-benbolt.xml
mv L0249.xml buckingham-aggravatingsam.xml
mv L0250.xml buckstone-aroughdiamond.xml
#mv L0262.xml lacy-cinderella.xml
mv L0271.xml planche-thegoldenbranch.xml
mv L0283.xml planche-thesleepingbeauty.xml
#mv L0287.xml planche-thebirds.xml
mv L0296.xml planche-theirishpost.xml
mv L0313.xml lewes-achainofevents.xml
mv L0321.xml planche-thegarrickfever.xml
mv L0327.xml morton-howstoutyouregetting.xml
mv L0359.xml oxenford-twicekilled.xml
mv L0378.xml pitt-thejerseygirl.xml
mv L0399.xml paul-lockedout.xml
mv L0406.xml brough-perdita.xml
mv L0418.xml wilks-bamboozling.xml
mv L0466.xml bernard-marieducange.xml
mv L0491.xml robertson-twogaydeceivers.xml
mv L0494.xml almar-olivertwist.xml
mv L0499.xml coyne-whatwilltheysay.xml
mv L0526.xml dance-marriagealottery.xml
mv L0567.xml cavendish-thewomanoftheworld.xml
#mv L0584.xml rowe-janeshore.xml
mv L0592.xml williams-icionparlefrançais.xml
mv L0599.xml stirling-theriflevolunteers.xml
mv L0605.xml oxenford-retainedforthedefence.xml
mv L0610.xml simpson-theschoolforcoquettes.xml
mv L0611.xml harris-ruthven.xml
mv L0652.xml jerrold-beaubrummel.xml
mv L0691.xml archer-margueritescolours.xml
mv L0707.xml marston-ahardstruggle.xml
mv L0727.xml byron-robinsoncrusoe.xml
mv L0737.xml taylor-upatthehills.xml
mv L0743.xml robertson-thecantab.xml
mv L0770.xml anon-maryprice.xml
mv L0783.xml heron-medea.xml
mv L0796.xml burnand-villikinsandhisdinah.xml
mv L0819.xml brough-thecolleenbawnsettled.xml
mv L0843.xml brough-rasselas.xml
mv L0845.xml williams-cartedevisite.xml
mv L0848.xml suter-dred.xml
mv L0849.xml suter-ladyaudleyssecret.xml
mv L0881.xml phillips-hislastvictory.xml
mv L0911.xml byron-1863.xml
mv L0932.xml boucicault-thecolleenbawn.xml
mv L0945.xml morton-woodcockslittlegame.xml
mv L0963.xml boucicault-theoctoroon.xml
mv L0979.xml suter-wantedayounglady.xml
mv L0993.xml byron-wartotheknife.xml
mv L1058.xml haines-mypollandmypartnerjoe.xml
mv L1060.xml robertson-society.xml
mv L1124.xml milner-frankenstein.xml
mv L1183.xml macready-theirishmaninlondon.xml
mv L1188.xml williams-thepeepshowman.xml
mv L1201.xml daly-underthegaslight.xml
mv L1246.xml phillips-notguilty.xml
mv L1263.xml gilbert-anoldscore.xml
mv L1285.xml jerrold-ambrosegwinett.xml
mv L1288.xml cheltnam-graceholden.xml
mv L1300.xml hazlewood-flowermakers.xml
mv L1315.xml byron-thecorsicanbothers.xml
mv L1326.xml horne-thedeathofmarlowe.xml
mv L1330.xml berrie-captainsmith.xml
mv L1360.xml vicars-inthreevolumes.xml
mv L1379.xml coyne-thewomaninred.xml
mv L1388.xml anon-aftertheparty.xml
mv L1412.xml reeve-neverreckon.xml
mv L1423.xml reece-theverylastdays.xml
mv L1434.xml milner-mazeppa.xml
mv L1447.xml lewis-thebells.xml
mv L1460.xml gilbert-onguard.xml
mv L1468.xml poole-scapegoat.xml
mv L1470.xml amherst-thebattleofwaterloo.xml
mv L1478.xml abeckett-thelastofthelegends.xml
mv L1499.xml merivale-ahusbandinclover.xml
mv L1500.xml maltby-yourvoteandinterest.xml

# //bibl[@type='origin']/concat('mv ',ancestor::TEI/@xml:id,'.xml',substring-before(lower-case(author[1]),','), '-', title[@type='main']/@n)
~/
