# this maps Lacy IDs to Dracor-friendly filenames
# there should be an entry here for every title included in the sample
# some files are commented out because they fail validation
cp ~/Public/Lacy/TEI/L0001.xml courtney-timetriesall.xml
cp ~/Public/Lacy/TEI/L0012.xml brooks-thecreole.xml
cp ~/Public/Lacy/TEI/L0013.xml taylor-noveltyfair.xml
cp ~/Public/Lacy/TEI/L0039.xml courtney-belphegor.xml
cp ~/Public/Lacy/TEI/L0042R.xml townley-highlife.xml
cp ~/Public/Lacy/TEI/L0044.xml brooks-theexposition.xml
cp ~/Public/Lacy/TEI/L0048.xml brough-apartments.xml
cp ~/Public/Lacy/TEI/L0053.xml brooks-anythingforachange.xml
cp ~/Public/Lacy/TEI/L0057R.xml massinger-anewwaytopayolddebts.xml
cp ~/Public/Lacy/TEI/L0066.xml morton-athumpinglegacy.xml
cp ~/Public/Lacy/TEI/L0073.xml morton-boxandcox.xml
cp ~/Public/Lacy/TEI/L0075.xml phillips-anorganicaffection.xml
cp ~/Public/Lacy/TEI/L0076.xml coyne-aduelinthedark.xml
cp ~/Public/Lacy/TEI/L0082.xml barrymore-elhyder.xml
cp ~/Public/Lacy/TEI/L0105.xml phillips-themasterpassion.xml
cp ~/Public/Lacy/TEI/L0106.xml boucicault-theprimadonna.xml
cp ~/Public/Lacy/TEI/L0113.xml coyne-boxandcoxmarried.xml
cp ~/Public/Lacy/TEI/L0118.xml morton-betseybaker.xml
cp ~/Public/Lacy/TEI/L0124.xml planche-theloanofalover.xml
cp ~/Public/Lacy/TEI/L0127.xml barnett-thebolddragoons.xml
cp ~/Public/Lacy/TEI/L0132.xml shakespeare-macbeth.xml
cp ~/Public/Lacy/TEI/L0142.xml dimond-stagestruck.xml
cp ~/Public/Lacy/TEI/L0144.xml morton-adesperategame.xml
cp ~/Public/Lacy/TEI/L0157.xml planche-ahandsomehusband.xml
cp ~/Public/Lacy/TEI/L0170.xml planche-thecampattheolympic.xml
cp ~/Public/Lacy/TEI/L0179.xml fitzball-themillerofderwent.xml
cp ~/Public/Lacy/TEI/L0191.xml taylor-plotandpassion.xml
cp ~/Public/Lacy/TEI/L0197.xml coyne-willikindandhisdinah.xml
cp ~/Public/Lacy/TEI/L0201.xml planche-thejacobite.xml
cp ~/Public/Lacy/TEI/L0206.xml poole-twouldpuzzleaconjuror.xml
cp ~/Public/Lacy/TEI/L0219.xml morton-waitingforanomnibus.xml
cp ~/Public/Lacy/TEI/L0228.xml johnstone-benbolt.xml
cp ~/Public/Lacy/TEI/L0249.xml buckingham-aggravatingsam.xml
cp ~/Public/Lacy/TEI/L0250.xml buckstone-aroughdiamond.xml
cp ~/Public/Lacy/TEI/L0271.xml planche-thegoldenbranch.xml
cp ~/Public/Lacy/TEI/L0283.xml planche-thesleepingbeauty.xml
cp ~/Public/Lacy/TEI/L0296.xml planche-theirishpost.xml
cp ~/Public/Lacy/TEI/L0313.xml lewes-achainofevents.xml
cp ~/Public/Lacy/TEI/L0321.xml planche-thegarrickfever.xml
cp ~/Public/Lacy/TEI/L0327.xml morton-howstoutyouregetting.xml
cp ~/Public/Lacy/TEI/L0359.xml oxenford-twicekilled.xml
cp ~/Public/Lacy/TEI/L0378.xml pitt-thejerseygirl.xml
cp ~/Public/Lacy/TEI/L0399.xml paul-lockedout.xml
cp ~/Public/Lacy/TEI/L0406.xml brough-perdita.xml
cp ~/Public/Lacy/TEI/L0418.xml wilks-bamboozling.xml
cp ~/Public/Lacy/TEI/L0466.xml bernard-marieducange.xml
cp ~/Public/Lacy/TEI/L0491.xml robertson-twogaydeceivers.xml
cp ~/Public/Lacy/TEI/L0494.xml almar-olivertwist.xml
cp ~/Public/Lacy/TEI/L0499.xml coyne-whatwilltheysay.xml
cp ~/Public/Lacy/TEI/L0526.xml dance-marriagealottery.xml
cp ~/Public/Lacy/TEI/L0567.xml cavendish-thewomanoftheworld.xml
cp ~/Public/Lacy/TEI/L0592.xml williams-icionparlefrançais.xml
cp ~/Public/Lacy/TEI/L0599.xml stirling-theriflevolunteers.xml
cp ~/Public/Lacy/TEI/L0605.xml oxenford-retainedforthedefence.xml
cp ~/Public/Lacy/TEI/L0610.xml simpson-theschoolforcoquettes.xml
cp ~/Public/Lacy/TEI/L0611.xml harris-ruthven.xml
cp ~/Public/Lacy/TEI/L0652.xml jerrold-beaubrummel.xml
cp ~/Public/Lacy/TEI/L0691.xml archer-margueritescolours.xml
cp ~/Public/Lacy/TEI/L0707.xml marston-ahardstruggle.xml
cp ~/Public/Lacy/TEI/L0727.xml byron-robinsoncrusoe.xml
cp ~/Public/Lacy/TEI/L0737.xml taylor-upatthehills.xml
cp ~/Public/Lacy/TEI/L0743.xml robertson-thecantab.xml
cp ~/Public/Lacy/TEI/L0770.xml anon-maryprice.xml
cp ~/Public/Lacy/TEI/L0783.xml heron-medea.xml
cp ~/Public/Lacy/TEI/L0796.xml burnand-villikinsandhisdinah.xml
cp ~/Public/Lacy/TEI/L0819.xml brough-thecolleenbawnsettled.xml
cp ~/Public/Lacy/TEI/L0843.xml brough-rasselas.xml
cp ~/Public/Lacy/TEI/L0845.xml williams-cartedevisite.xml
cp ~/Public/Lacy/TEI/L0848.xml suter-dred.xml
cp ~/Public/Lacy/TEI/L0849.xml suter-ladyaudleyssecret.xml
cp ~/Public/Lacy/TEI/L0881.xml phillips-hislastvictory.xml
cp ~/Public/Lacy/TEI/L0911.xml byron-1863.xml
cp ~/Public/Lacy/TEI/L0932.xml boucicault-thecolleenbawn.xml
cp ~/Public/Lacy/TEI/L0945.xml morton-woodcockslittlegame.xml
cp ~/Public/Lacy/TEI/L0963.xml boucicault-theoctoroon.xml
cp ~/Public/Lacy/TEI/L0979.xml suter-wantedayounglady.xml
cp ~/Public/Lacy/TEI/L0993.xml byron-wartotheknife.xml
cp ~/Public/Lacy/TEI/L1058.xml haines-mypollandmypartnerjoe.xml
cp ~/Public/Lacy/TEI/L1060.xml robertson-society.xml
cp ~/Public/Lacy/TEI/L1124.xml milner-frankenstein.xml
cp ~/Public/Lacy/TEI/L1183.xml macready-theirishmaninlondon.xml
cp ~/Public/Lacy/TEI/L1188.xml williams-thepeepshowman.xml
cp ~/Public/Lacy/TEI/L1201.xml daly-underthegaslight.xml
cp ~/Public/Lacy/TEI/L1246.xml phillips-notguilty.xml
cp ~/Public/Lacy/TEI/L1263.xml gilbert-anoldscore.xml
cp ~/Public/Lacy/TEI/L1285.xml jerrold-ambrosegwinett.xml
cp ~/Public/Lacy/TEI/L1288.xml cheltnam-graceholden.xml
cp ~/Public/Lacy/TEI/L1300.xml hazlewood-flowermakers.xml
cp ~/Public/Lacy/TEI/L1315.xml byron-thecorsicanbothers.xml
cp ~/Public/Lacy/TEI/L1326.xml horne-thedeathofmarlowe.xml
cp ~/Public/Lacy/TEI/L1330.xml berrie-captainsmith.xml
cp ~/Public/Lacy/TEI/L1360.xml vicars-inthreevolumes.xml
cp ~/Public/Lacy/TEI/L1379.xml coyne-thewomaninred.xml
cp ~/Public/Lacy/TEI/L1388.xml anon-aftertheparty.xml
cp ~/Public/Lacy/TEI/L1412.xml reeve-neverreckon.xml
cp ~/Public/Lacy/TEI/L1423.xml reece-theverylastdays.xml
cp ~/Public/Lacy/TEI/L1434.xml milner-mazeppa.xml
cp ~/Public/Lacy/TEI/L1447.xml lewis-thebells.xml
cp ~/Public/Lacy/TEI/L1460.xml gilbert-onguard.xml
cp ~/Public/Lacy/TEI/L1468.xml poole-scapegoat.xml
cp ~/Public/Lacy/TEI/L1470.xml amherst-thebattleofwaterloo.xml
cp ~/Public/Lacy/TEI/L1478.xml abeckett-thelastofthelegends.xml
cp ~/Public/Lacy/TEI/L1499.xml merivale-ahusbandinclover.xml
cp ~/Public/Lacy/TEI/L1500.xml maltby-yourvoteandinterest.xml
